Remove file with invalid trailing space in name
File has a space after the filename, which is wrong and breaks git on linux 
>error: invalid path 'docs/code-snippets/troubleshooting-codesnippets.md '

Remove the file, since it's empty anyway. If it's needed, can be recreated with correct name without trailing space